### ISSUE TITLE
Adjustable detection sensitivity

### ISSUE THREAD

**Issue by CustomPhase** [DanielSWolf/rhubarb-lip-sync#11] opened 2017-04-08 20:55 UTC
Hey, thanks for the awesome work you do. However ive had some problems with breathing sounds registering as phonemes and sometimes in clear long phonemes (like holding AAH, or OOH for a long time) it can switch to other phonemes that arent there for a brief period. Can we please get some sort of adjustable sensitivity of the detection algorithm or something along those lines?

**Comment by DanielSWolf** [comment] 2017-04-09 18:45
That shouldn't happen. It's by design that breathing sounds are detected and animated; after all, it would look odd to hear the breathing, but not see it. But breathing should only result in B or C shapes, not in distracting animation.

Please send me a WAVE file that reproduces the problem. Also, are you using the latest version of Rhubarb (1.4.2)?

**Comment by DanielSWolf** [comment] 2017-04-19 19:15
I haven't received any data to reproduce this problem, so I'm closing the issue for the time being. If anybody can reproduce this, feel free to comment and I'll re-open the issue.

**Closed by DanielSWolf** 2017-04-19 19:15 UTC
