### ISSUE TITLE
Build support for Linux

### ISSUE THREAD

**Issue by whatisor** [DanielSWolf/rhubarb-lip-sync#1] opened 2016-08-13 02:03 UTC

**Comment by DanielSWolf** [comment] 2016-08-13 12:56
So far, I've only tested the build on Windows and OS X. But given that most of the code is platform-agnostic, building on Unix systems other than OS X shouldn't be a problem. My guess is that it'll either work out of the box, or you'll have to perform minor tweaks to `CMakeLists.txt` or `src/platformTools.cpp`. Just try it out and let me know your results! (You'll need CMake and Boost installed.)

By the way: What specific OS do you have in mind?

**Comment by whatisor** [comment] 2016-08-18 15:38
Hi, I am using Ubuntu 15.04.
After I add add_definitions( -DHAVE_UNISTD_H ) on cmakelist, it can overcome some error, but still get this:
/home/karoshi/LipSync/rhubarb-lip-sync-master/src/Timeline.h: In instantiation of ‘Timeline<T>::iterator Timeline<T>::find(Timeline<T>::time_type, FindMode) const [with T = Shape; Timeline<T>::iterator = std::_Rb_tree_const_iterator<Timed<Shape> >; Timeline<T>::time_type = std::chrono::duration<int, std::ratio<1l, 100l> >]’:
/home/karoshi/LipSync/rhubarb-lip-sync-master/src/Timeline.h:190:62:   required from ‘void Timeline<T>::clear(const TimeRange&) [with T = Shape]’
/home/karoshi/LipSync/rhubarb-lip-sync-master/src/main.cpp:208:1:   required from here
/home/karoshi/LipSync/rhubarb-lip-sync-master/src/Timeline.h:154:43: error: no matching function for call to ‘std::set<Timed<Shape>, Timeline<Shape>::compare, std::allocator<Timed<Shape> > >::lower_bound(Timeline<Shape>::time_type&) const’
    iterator it = elements.lower_bound(time);

I spent some hours to find, but no idea :(
Thank you

**Comment by DanielSWolf** [comment] 2016-08-20 18:44
I'm currently on vacation, but I'll look into it once I'm back (in about a week).

Until then, you could give me some more information about your system. What compiler in what version do you use, and what versions of CMake and Boost do you use?

**Comment by whatisor** [comment] 2016-08-22 15:01
Hi,
My environment is:
+ Ubuntu 15.04 :  3.19.0-42-generic #48-Ubuntu SMP Thu Dec 17 22:54:45 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
+ cmake version 3.6.1
+ boost 1.55 (libboost_atomic.so.1.55.0,libboost_chrono.so.1.55.0,....)
+ compiler : c++ (Ubuntu 4.9.2-10ubuntu13) 4.9.2
Thank you so much.

**Comment by DanielSWolf** [comment] 2016-08-30 21:28
I've started trying to get Rhubarb to build on Ubuntu. So far, I've found the missing `HAVE_UNISTD_H` you mentioned as well as multiple issues with the capitalization of file names (that's what you get for using case-insensitive file systems!).

I haven't progressed to your specific error yet, but I'm getting there.

**Comment by whatisor** [comment] 2016-08-31 06:45
Yes, you are correct. I fixed Capitalization errors before :)

**Comment by DanielSWolf** [comment] 2016-08-31 20:26
Okay... there were lots of small things preventing the Linux build from succeeding, but now it's working for me. Strangely enough, I never encountered your exact error.

Let me know whether it's working for you!

**Comment by whatisor** [comment] 2016-09-01 10:40
oh, you mean you commited new code?

**Comment by whatisor** [comment] 2016-09-05 11:49
It is much better but I got same error :(



[  1%] Built target cppFormat
[ 25%] Built target sphinxbase
[ 38%] Built target pocketSphinx
[ 39%] Built target whereami
[ 48%] Built target webRTC
[ 74%] Built target flite
[ 74%] Building CXX object CMakeFiles/rhubarb.dir/src/main.cpp.o
In file included from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/TimeRange.h:2:0,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/audio/AudioClip.h:3,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/audio/WaveFileReader.h:4,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/main.cpp:5:
/home/nxhuong/Downloads/rhubarb-lip-sync-master/src/centiseconds.h:10:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(push)
 ^
/home/nxhuong/Downloads/rhubarb-lip-sync-master/src/centiseconds.h:11:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable: 4455)
 ^
/home/nxhuong/Downloads/rhubarb-lip-sync-master/src/centiseconds.h:15:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(pop)
 ^
In file included from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/BoundedTimeline.h:3:0,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/phoneExtraction.h:6,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/main.cpp:6:
/home/nxhuong/Downloads/rhubarb-lip-sync-master/src/Timeline.h: In instantiation of ‘Timeline<T>::iterator Timeline<T>::find(Timeline<T>::time_type, FindMode) const [with T = Shape; Timeline<T>::iterator = std::_Rb_tree_const_iterator<Timed<Shape> >; Timeline<T>::time_type = std::chrono::duration<int, std::ratio<1l, 100l> >]’:
/home/nxhuong/Downloads/rhubarb-lip-sync-master/src/Timeline.h:190:62:   required from ‘void Timeline<T>::clear(const TimeRange&) [with T = Shape]’
/home/nxhuong/Downloads/rhubarb-lip-sync-master/src/main.cpp:208:1:   required from here
/home/nxhuong/Downloads/rhubarb-lip-sync-master/src/Timeline.h:154:43: error: no matching function for call to ‘std::set<Timed<Shape>, Timeline<Shape>::compare, std::allocator<Timed<Shape> > >::lower_bound(Timeline<Shape>::time_type&) const’
    iterator it = elements.lower_bound(time);
                                           ^
/home/nxhuong/Downloads/rhubarb-lip-sync-master/src/Timeline.h:154:43: note: candidates are:
In file included from /usr/include/c++/4.9/set:61:0,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/Timeline.h:3,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/BoundedTimeline.h:3,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/phoneExtraction.h:6,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/main.cpp:6:
/usr/include/c++/4.9/bits/stl_set.h:722:7: note: std::set<_Key, _Compare, _Alloc>::iterator std::set<_Key, _Compare, _Alloc>::lower_bound(const key_type&) [with _Key = Timed<Shape>; _Compare = Timeline<Shape>::compare; _Alloc = std::allocator<Timed<Shape> >; std::set<_Key, _Compare, _Alloc>::iterator = std::_Rb_tree_const_iterator<Timed<Shape> >; std::set<_Key, _Compare, _Alloc>::key_type = Timed<Shape>]
       lower_bound(const key_type& __x)
       ^
/usr/include/c++/4.9/bits/stl_set.h:722:7: note:   no known conversion for argument 1 from ‘Timeline<Shape>::time_type {aka std::chrono::duration<int, std::ratio<1l, 100l> >}’ to ‘const key_type& {aka const Timed<Shape>&}’
/usr/include/c++/4.9/bits/stl_set.h:726:7: note: std::set<_Key, _Compare, _Alloc>::const_iterator std::set<_Key, _Compare, _Alloc>::lower_bound(const key_type&) const [with _Key = Timed<Shape>; _Compare = Timeline<Shape>::compare; _Alloc = std::allocator<Timed<Shape> >; std::set<_Key, _Compare, _Alloc>::const_iterator = std::_Rb_tree_const_iterator<Timed<Shape> >; std::set<_Key, _Compare, _Alloc>::key_type = Timed<Shape>]
       lower_bound(const key_type& __x) const
       ^
/usr/include/c++/4.9/bits/stl_set.h:726:7: note:   no known conversion for argument 1 from ‘Timeline<Shape>::time_type {aka std::chrono::duration<int, std::ratio<1l, 100l> >}’ to ‘const key_type& {aka const Timed<Shape>&}’
In file included from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/BoundedTimeline.h:3:0,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/phoneExtraction.h:6,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/main.cpp:6:
/home/nxhuong/Downloads/rhubarb-lip-sync-master/src/Timeline.h:161:43: error: no matching function for call to ‘std::set<Timed<Shape>, Timeline<Shape>::compare, std::allocator<Timed<Shape> > >::upper_bound(Timeline<Shape>::time_type&) const’
    iterator it = elements.upper_bound(time);
                                           ^
/home/nxhuong/Downloads/rhubarb-lip-sync-master/src/Timeline.h:161:43: note: candidates are:
In file included from /usr/include/c++/4.9/set:61:0,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/Timeline.h:3,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/BoundedTimeline.h:3,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/phoneExtraction.h:6,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/main.cpp:6:
/usr/include/c++/4.9/bits/stl_set.h:738:7: note: std::set<_Key, _Compare, _Alloc>::iterator std::set<_Key, _Compare, _Alloc>::upper_bound(const key_type&) [with _Key = Timed<Shape>; _Compare = Timeline<Shape>::compare; _Alloc = std::allocator<Timed<Shape> >; std::set<_Key, _Compare, _Alloc>::iterator = std::_Rb_tree_const_iterator<Timed<Shape> >; std::set<_Key, _Compare, _Alloc>::key_type = Timed<Shape>]
       upper_bound(const key_type& __x)
       ^
/usr/include/c++/4.9/bits/stl_set.h:738:7: note:   no known conversion for argument 1 from ‘Timeline<Shape>::time_type {aka std::chrono::duration<int, std::ratio<1l, 100l> >}’ to ‘const key_type& {aka const Timed<Shape>&}’
/usr/include/c++/4.9/bits/stl_set.h:742:7: note: std::set<_Key, _Compare, _Alloc>::const_iterator std::set<_Key, _Compare, _Alloc>::upper_bound(const key_type&) const [with _Key = Timed<Shape>; _Compare = Timeline<Shape>::compare; _Alloc = std::allocator<Timed<Shape> >; std::set<_Key, _Compare, _Alloc>::const_iterator = std::_Rb_tree_const_iterator<Timed<Shape> >; std::set<_Key, _Compare, _Alloc>::key_type = Timed<Shape>]
       upper_bound(const key_type& __x) const
       ^
/usr/include/c++/4.9/bits/stl_set.h:742:7: note:   no known conversion for argument 1 from ‘Timeline<Shape>::time_type {aka std::chrono::duration<int, std::ratio<1l, 100l> >}’ to ‘const key_type& {aka const Timed<Shape>&}’
In file included from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/BoundedTimeline.h:3:0,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/phoneExtraction.h:6,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/main.cpp:6:
/home/nxhuong/Downloads/rhubarb-lip-sync-master/src/Timeline.h: In instantiation of ‘Timeline<T>::iterator Timeline<T>::find(Timeline<T>::time_type, FindMode) const [with T = Phone; Timeline<T>::iterator = std::_Rb_tree_const_iterator<Timed<Phone> >; Timeline<T>::time_type = std::chrono::duration<int, std::ratio<1l, 100l> >]’:
/home/nxhuong/Downloads/rhubarb-lip-sync-master/src/Timeline.h:190:62:   required from ‘void Timeline<T>::clear(const TimeRange&) [with T = Phone]’
/home/nxhuong/Downloads/rhubarb-lip-sync-master/src/main.cpp:208:1:   required from here
/home/nxhuong/Downloads/rhubarb-lip-sync-master/src/Timeline.h:154:43: error: no matching function for call to ‘std::set<Timed<Phone>, Timeline<Phone>::compare, std::allocator<Timed<Phone> > >::lower_bound(Timeline<Phone>::time_type&) const’
    iterator it = elements.lower_bound(time);
                                           ^
/home/nxhuong/Downloads/rhubarb-lip-sync-master/src/Timeline.h:154:43: note: candidates are:
In file included from /usr/include/c++/4.9/set:61:0,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/Timeline.h:3,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/BoundedTimeline.h:3,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/phoneExtraction.h:6,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/main.cpp:6:
/usr/include/c++/4.9/bits/stl_set.h:722:7: note: std::set<_Key, _Compare, _Alloc>::iterator std::set<_Key, _Compare, _Alloc>::lower_bound(const key_type&) [with _Key = Timed<Phone>; _Compare = Timeline<Phone>::compare; _Alloc = std::allocator<Timed<Phone> >; std::set<_Key, _Compare, _Alloc>::iterator = std::_Rb_tree_const_iterator<Timed<Phone> >; std::set<_Key, _Compare, _Alloc>::key_type = Timed<Phone>]
       lower_bound(const key_type& __x)
       ^
/usr/include/c++/4.9/bits/stl_set.h:722:7: note:   no known conversion for argument 1 from ‘Timeline<Phone>::time_type {aka std::chrono::duration<int, std::ratio<1l, 100l> >}’ to ‘const key_type& {aka const Timed<Phone>&}’
/usr/include/c++/4.9/bits/stl_set.h:726:7: note: std::set<_Key, _Compare, _Alloc>::const_iterator std::set<_Key, _Compare, _Alloc>::lower_bound(const key_type&) const [with _Key = Timed<Phone>; _Compare = Timeline<Phone>::compare; _Alloc = std::allocator<Timed<Phone> >; std::set<_Key, _Compare, _Alloc>::const_iterator = std::_Rb_tree_const_iterator<Timed<Phone> >; std::set<_Key, _Compare, _Alloc>::key_type = Timed<Phone>]
       lower_bound(const key_type& __x) const
       ^
/usr/include/c++/4.9/bits/stl_set.h:726:7: note:   no known conversion for argument 1 from ‘Timeline<Phone>::time_type {aka std::chrono::duration<int, std::ratio<1l, 100l> >}’ to ‘const key_type& {aka const Timed<Phone>&}’
In file included from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/BoundedTimeline.h:3:0,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/phoneExtraction.h:6,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/main.cpp:6:
/home/nxhuong/Downloads/rhubarb-lip-sync-master/src/Timeline.h:161:43: error: no matching function for call to ‘std::set<Timed<Phone>, Timeline<Phone>::compare, std::allocator<Timed<Phone> > >::upper_bound(Timeline<Phone>::time_type&) const’
    iterator it = elements.upper_bound(time);
                                           ^
/home/nxhuong/Downloads/rhubarb-lip-sync-master/src/Timeline.h:161:43: note: candidates are:
In file included from /usr/include/c++/4.9/set:61:0,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/Timeline.h:3,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/BoundedTimeline.h:3,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/phoneExtraction.h:6,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/main.cpp:6:
/usr/include/c++/4.9/bits/stl_set.h:738:7: note: std::set<_Key, _Compare, _Alloc>::iterator std::set<_Key, _Compare, _Alloc>::upper_bound(const key_type&) [with _Key = Timed<Phone>; _Compare = Timeline<Phone>::compare; _Alloc = std::allocator<Timed<Phone> >; std::set<_Key, _Compare, _Alloc>::iterator = std::_Rb_tree_const_iterator<Timed<Phone> >; std::set<_Key, _Compare, _Alloc>::key_type = Timed<Phone>]
       upper_bound(const key_type& __x)
       ^
/usr/include/c++/4.9/bits/stl_set.h:738:7: note:   no known conversion for argument 1 from ‘Timeline<Phone>::time_type {aka std::chrono::duration<int, std::ratio<1l, 100l> >}’ to ‘const key_type& {aka const Timed<Phone>&}’
/usr/include/c++/4.9/bits/stl_set.h:742:7: note: std::set<_Key, _Compare, _Alloc>::const_iterator std::set<_Key, _Compare, _Alloc>::upper_bound(const key_type&) const [with _Key = Timed<Phone>; _Compare = Timeline<Phone>::compare; _Alloc = std::allocator<Timed<Phone> >; std::set<_Key, _Compare, _Alloc>::const_iterator = std::_Rb_tree_const_iterator<Timed<Phone> >; std::set<_Key, _Compare, _Alloc>::key_type = Timed<Phone>]
       upper_bound(const key_type& __x) const
       ^
/usr/include/c++/4.9/bits/stl_set.h:742:7: note:   no known conversion for argument 1 from ‘Timeline<Phone>::time_type {aka std::chrono::duration<int, std::ratio<1l, 100l> >}’ to ‘const key_type& {aka const Timed<Phone>&}’
make[2]: *** [CMakeFiles/rhubarb.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/rhubarb.dir/all] Error 2
make: *** [all] Error 2

**Comment by DanielSWolf** [comment] 2016-09-07 15:52
At this point, my guess is that the problem is not with the code, but with your compiler. What version of what compiler (gcc or clang) do you use? -- You might try upgrading to the latest gcc.

**Comment by DanielSWolf** [comment] 2016-09-08 19:41
During the process of setting up a Travis build, I managed to reproduce the problem. Since C++14, [std::set::lower_bound()](http://en.cppreference.com/w/cpp/container/set/lower_bound) has two additional overloads. Your compiler doesn't seem to find them.

I'll try to find a solution and keep this issue updated.

**Comment by whatisor** [comment] 2016-09-09 07:55
Hi, thank for your info.
It works with g++6. but other issue:
In file included from /usr/local/include/boost/optional/optional.hpp:1035:0,
                 from /usr/local/include/boost/optional.hpp:15,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/Timeline.h:4,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/tests/TimelineTests.cpp:2:
/usr/local/include/boost/optional/detail/optional_reference_spec.hpp: In instantiation of ‘boost::optional<T&>::optional(R&&, typename boost::enable_if<boost::detail::is_no_optional<R> >::type*) [with R = Timeline<int>::ReferenceWrapper; T = const int; typename boost::enable_if<boost::detail::is_no_optional<R> >::type = void]’:
/home/nxhuong/Downloads/rhubarb-lip-sync-master/tests/TimelineTests.cpp:225:44:   required from here
/usr/local/include/boost/optional/detail/optional_reference_spec.hpp:126:35: error: cannot convert ‘Timeline<int>::ReferenceWrapper*’ to ‘const int*’ in initialization
         : ptr_(boost::addressof(r)) { detail::prevent_binding_rvalue<R>(); }
                                   ^
In file included from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/TimeRange.h:2:0,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/audio/AudioClip.h:3,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/audio/WaveFileReader.h:4,
                 from /home/nxhuong/Downloads/rhubarb-lip-sync-master/src/main.cpp:5:

Do you think it is boost version issue?

**Comment by whatisor** [comment] 2016-09-09 08:31
I am using boost 6.1

**Comment by whatisor** [comment] 2016-09-09 08:37
I REMOVED test project from CMakelist and it worked as charm.
Please help to check test project if you have time.
Thank so much.

**Comment by whatisor** [comment] 2016-09-09 09:16
I've try with some wav files. I always got this message:
Analyzing input file                                       


An error occurred.
Could not open sound file '/home/nxhuong/Downloads/8ktruespeech.wav'.
Unsupported sample format. Only uncompressed formats are supported.

**Comment by DanielSWolf** [comment] 2016-09-09 12:25
Hi @whatisor, I'm glad the build is working for you now. I'm working on setting up a working Travis build so that the problems you're having with the test project should disappear in a few days.

Regarding WAVE format support: Most sound editors will save uncompressed WAVE files. Compressed WAVE files are rather rare (and not supported by Rhubarb). If you're having any trouble with Rhubarb's handling of sound file, feel free to create a new issue!

**Comment by DanielSWolf** [comment] 2016-09-11 09:57
@whatisor: The Linux build should work fine now, so I'm closing this issue. I've set up a [Travis CI project](https://travis-ci.org/DanielSWolf/rhubarb-lip-sync) for Linux and OS X, so I'll be notified if anything breaks.

Regarding the test project: It builds just fine for me. If you're still having trouble with it, feel free to create another issue.

**Closed by DanielSWolf** 2016-09-11 09:57 UTC

**Comment by jeffinrp** [comment] 2018-05-31 06:42
rhubarb: command not found
